### ISSUE TITLE
Patches not applying with v0.12.0

### ISSUE THREAD

**Issue by jacobtomlinson** [elemental-lf/k8s-crd-resolver#4]
I was halfway through opening this issue when I noticed you pushed `v0.14.0` an hour ago and it fixes the problem. Thanks!

**Comment by elemental-lf** [comment]
@jacobtomlinson yeah, sorry for releasing a bunch of versions in such a short time frame. I was a little distracted and wasn't testing properly.

**Comment by jacobtomlinson** [comment]
No worries at all! Lots of fast releases in one day is better than no releases for months 😂. 

Thanks again for all the hard work.
